import type { Restaurant } from "../../src/lib/types";

const standardHours = [
  { day: "Mon", hours: "11:30 AM – 10:30 PM" },
  { day: "Tue", hours: "11:30 AM – 10:30 PM" },
  { day: "Wed", hours: "11:30 AM – 10:30 PM" },
  { day: "Thu", hours: "11:30 AM – 10:30 PM" },
  { day: "Fri", hours: "11:30 AM – 11:30 PM" },
  { day: "Sat", hours: "11:30 AM – 11:30 PM" },
  { day: "Sun", hours: "10:00 AM – 10:00 PM" },
];

export const restaurants: Restaurant[] = [
  {
    id: "r1",
    slug: "cinnamon-and-salt",
    name: "Cinnamon & Salt",
    tagline: "Waterfront seafood grill overlooking the harbour",
    area: "Fort (Colombo 1)",
    address: "12 Chaithya Road, Colombo 1",
    lat: 6.9344,
    lng: 79.8428,
    cuisines: ["seafood", "asian-fusion"],
    rating: 4.8,
    reviewCount: 421,
    priceLevel: 4,
    imageSeed: "onit-dine-1",
    gallerySeeds: ["onit-dine-1a", "onit-dine-1b", "onit-dine-1c"],
    about:
      "Cinnamon & Salt sources its catch each morning from Mutwal fish market. Open-air seating looks straight onto the harbour, with a charcoal grill open to view.",
    amenities: ["Outdoor seating", "Full bar", "Waterfront view", "Valet parking"],
    menuHighlights: [
      { id: "r1-1", name: "Charcoal Grilled Jumbo Prawns", priceLKR: 4200, description: "Chilli-lime marinade, coconut sambol." },
      { id: "r1-2", name: "Whole Grilled Seer Fish", priceLKR: 6800, description: "Serves 2, tamarind glaze." },
      { id: "r1-3", name: "Crab Curry", priceLKR: 5400, description: "Black pepper crab curry, roti." },
    ],
    partySizes: [2, 3, 4, 5, 6, 8],
    openHours: standardHours,
    reviews: [
      { id: "r1rev1", author: "Kavindu R.", rating: 5, date: "2026-06-20", comment: "Best crab curry in Colombo, hands down. Book ahead on weekends." },
      { id: "r1rev2", author: "Ishara W.", rating: 5, date: "2026-05-14", comment: "Table by the water at sunset was unforgettable." },
    ],
    featured: true,
    phone: "+94 11 232 1190",
  },
  {
    id: "r2",
    slug: "kade-no-9",
    name: "Kade No. 9",
    tagline: "Rice & curry and short eats, done properly",
    area: "Cinnamon Gardens (Colombo 7)",
    address: "9 Flower Road, Colombo 7",
    lat: 6.9096,
    lng: 79.8612,
    cuisines: ["sri-lankan"],
    rating: 4.7,
    reviewCount: 356,
    priceLevel: 2,
    imageSeed: "onit-dine-2",
    gallerySeeds: ["onit-dine-2a", "onit-dine-2b", "onit-dine-2c"],
    about:
      "A modern take on the neighbourhood kade — buffet-style rice and curry at lunch, à la carte hoppers and kottu through the evening.",
    amenities: ["Vegetarian options", "Family friendly", "Card & QR payments"],
    menuHighlights: [
      { id: "r2-1", name: "Rice & Curry Set", priceLKR: 1800, description: "Choice of 3 curries, papadam, sambol." },
      { id: "r2-2", name: "Egg Hoppers (3)", priceLKR: 850, description: "Classic bowl-shaped hoppers." },
      { id: "r2-3", name: "Kottu Roti", priceLKR: 1600, description: "Chicken or vegetable, wok-tossed." },
    ],
    partySizes: [2, 3, 4, 5, 6],
    openHours: standardHours,
    reviews: [
      { id: "r2rev1", author: "Nadeesha P.", rating: 5, date: "2026-06-11", comment: "Tastes like home cooking, but faster and tidier." },
      { id: "r2rev2", author: "Ruwan D.", rating: 4, date: "2026-05-02", comment: "Great value, gets busy at lunch so book ahead." },
    ],
    featured: true,
    phone: "+94 11 269 4410",
  },
  {
    id: "r3",
    slug: "spice-route-grill",
    name: "Spice Route Grill",
    tagline: "Tandoor and curries from across the subcontinent",
    area: "Colpetty (Colombo 3)",
    address: "31 Marine Drive, Colombo 3",
    lat: 6.9133,
    lng: 79.8452,
    cuisines: ["indian"],
    rating: 4.6,
    reviewCount: 268,
    priceLevel: 3,
    imageSeed: "onit-dine-3",
    gallerySeeds: ["onit-dine-3a", "onit-dine-3b", "onit-dine-3c"],
    about:
      "A working tandoor oven at the entrance sets the tone — smoky kebabs, slow-cooked curries, and breads made to order.",
    amenities: ["Full bar", "Vegetarian options", "Private dining room"],
    menuHighlights: [
      { id: "r3-1", name: "Tandoori Chicken (Half)", priceLKR: 2800, description: "Charred, yoghurt-marinated." },
      { id: "r3-2", name: "Butter Chicken", priceLKR: 2600, description: "Tomato-cashew gravy, served with naan." },
      { id: "r3-3", name: "Lamb Rogan Josh", priceLKR: 3400, description: "Kashmiri-style slow braise." },
    ],
    partySizes: [2, 3, 4, 5, 6, 8],
    openHours: standardHours,
    reviews: [
      { id: "r3rev1", author: "Areeba H.", rating: 5, date: "2026-06-03", comment: "The tandoori chicken alone is worth the visit." },
    ],
    featured: false,
    phone: "+94 11 257 8820",
  },
  {
    id: "r4",
    slug: "bella-notte",
    name: "Bella Notte",
    tagline: "Wood-fired pizza and handmade pasta",
    area: "Havelock Town (Colombo 5)",
    address: "58 Havelock Road, Colombo 5",
    lat: 6.8858,
    lng: 79.8695,
    cuisines: ["italian"],
    rating: 4.7,
    reviewCount: 302,
    priceLevel: 3,
    imageSeed: "onit-dine-4",
    gallerySeeds: ["onit-dine-4a", "onit-dine-4b", "onit-dine-4c"],
    about:
      "A neighbourhood Italian spot built around a wood-fired oven imported from Naples. Pasta is made fresh daily.",
    amenities: ["Outdoor seating", "Full bar", "Family friendly"],
    menuHighlights: [
      { id: "r4-1", name: "Margherita DOP", priceLKR: 2400, description: "San Marzano tomato, buffalo mozzarella." },
      { id: "r4-2", name: "Truffle Tagliatelle", priceLKR: 3200, description: "Fresh pasta, black truffle cream." },
      { id: "r4-3", name: "Tiramisu", priceLKR: 1200, description: "Classic, made in-house." },
    ],
    partySizes: [2, 3, 4, 5, 6],
    openHours: standardHours,
    reviews: [
      { id: "r4rev1", author: "Michelle F.", rating: 5, date: "2026-06-17", comment: "Best pizza crust in the city. Go for the margherita." },
      { id: "r4rev2", author: "Dinesh K.", rating: 4, date: "2026-04-28", comment: "Lovely outdoor seating, book ahead for weekends." },
    ],
    featured: true,
    phone: "+94 11 250 3367",
  },
  {
    id: "r5",
    slug: "lotus-and-ember",
    name: "Lotus & Ember",
    tagline: "Pan-Asian small plates and robata grill",
    area: "Rajagiriya",
    address: "77 Rajagiriya Road, Rajagiriya",
    lat: 6.9089,
    lng: 79.8987,
    cuisines: ["asian-fusion", "seafood"],
    rating: 4.8,
    reviewCount: 194,
    priceLevel: 3,
    imageSeed: "onit-dine-5",
    gallerySeeds: ["onit-dine-5a", "onit-dine-5b", "onit-dine-5c"],
    about:
      "Small plates built for sharing — Japanese robata grill technique meets Southeast Asian flavour across a compact, precise menu.",
    amenities: ["Full bar", "Private dining room", "Vegetarian options"],
    menuHighlights: [
      { id: "r5-1", name: "Robata Grilled Skewers", priceLKR: 2200, description: "Chicken, pork or tofu, per skewer." },
      { id: "r5-2", name: "Miso Black Cod", priceLKR: 4600, description: "48-hour miso marinade." },
      { id: "r5-3", name: "Wagyu Fried Rice", priceLKR: 3800, description: "Shaved wagyu, egg, scallion." },
    ],
    partySizes: [2, 3, 4, 5, 6],
    openHours: standardHours,
    reviews: [
      { id: "r5rev1", author: "Tashiya M.", rating: 5, date: "2026-06-09", comment: "Small menu, but everything on it is excellent." },
    ],
    featured: false,
    phone: "+94 11 288 4471",
  },
  {
    id: "r6",
    slug: "the-brunch-room",
    name: "The Brunch Room",
    tagline: "All-day brunch and specialty coffee",
    area: "Bambalapitiya (Colombo 4)",
    address: "134 Galle Road, Bambalapitiya, Colombo 4",
    lat: 6.8899,
    lng: 79.8562,
    cuisines: ["cafe-brunch", "bakery-dessert"],
    rating: 4.6,
    reviewCount: 289,
    priceLevel: 2,
    imageSeed: "onit-dine-6",
    gallerySeeds: ["onit-dine-6a", "onit-dine-6b", "onit-dine-6c"],
    about:
      "Bright, plant-filled, and built around a single-origin coffee program. The brunch menu runs from 7am to close.",
    amenities: ["Outdoor seating", "Free WiFi", "Vegetarian options", "Family friendly"],
    menuHighlights: [
      { id: "r6-1", name: "Avocado Toast", priceLKR: 1600, description: "Poached egg, chilli oil, sourdough." },
      { id: "r6-2", name: "Ricotta Hotcakes", priceLKR: 1800, description: "Honeycomb butter, seasonal fruit." },
      { id: "r6-3", name: "Flat White", priceLKR: 750, description: "House-roasted single origin." },
    ],
    partySizes: [2, 3, 4, 5, 6],
    openHours: standardHours,
    reviews: [
      { id: "r6rev1", author: "Sarah L.", rating: 5, date: "2026-06-15", comment: "My Saturday morning spot. Coffee is excellent." },
      { id: "r6rev2", author: "Yohan S.", rating: 4, date: "2026-05-20", comment: "Can get crowded after 9am, worth the wait." },
    ],
    featured: true,
    phone: "+94 11 259 3312",
  },
  {
    id: "r7",
    slug: "angus-and-oak",
    name: "Angus & Oak",
    tagline: "Dry-aged steaks and an oak-heavy wine list",
    area: "Cinnamon Gardens (Colombo 7)",
    address: "22 Horton Place, Colombo 7",
    lat: 6.9078,
    lng: 79.8628,
    cuisines: ["steakhouse"],
    rating: 4.9,
    reviewCount: 176,
    priceLevel: 4,
    imageSeed: "onit-dine-7",
    gallerySeeds: ["onit-dine-7a", "onit-dine-7b", "onit-dine-7c"],
    about:
      "A dedicated dry-aging room sits behind glass at the entrance. Cuts are aged in-house for a minimum of 28 days.",
    amenities: ["Full bar", "Private dining room", "Valet parking"],
    menuHighlights: [
      { id: "r7-1", name: "28-Day Dry-Aged Ribeye (300g)", priceLKR: 8500, description: "Bone-in, char-grilled." },
      { id: "r7-2", name: "Truffle Mac & Cheese", priceLKR: 2200, description: "Side, serves 2." },
      { id: "r7-3", name: "Molten Chocolate Fondant", priceLKR: 1600, description: "Vanilla bean ice cream." },
    ],
    partySizes: [2, 3, 4, 5, 6, 8],
    openHours: standardHours,
    reviews: [
      { id: "r7rev1", author: "Marc D.", rating: 5, date: "2026-06-01", comment: "The dry-aged ribeye is worth every rupee." },
      { id: "r7rev2", author: "Priyanka V.", rating: 5, date: "2026-04-11", comment: "Best steak in Colombo, no contest." },
    ],
    featured: true,
    phone: "+94 11 269 9021",
  },
  {
    id: "r8",
    slug: "sugar-and-rye",
    name: "Sugar & Rye",
    tagline: "Patisserie and dessert bar by the sea",
    area: "Mount Lavinia",
    address: "14 Beach Road, Mount Lavinia",
    lat: 6.8381,
    lng: 79.8641,
    cuisines: ["bakery-dessert", "cafe-brunch"],
    rating: 4.6,
    reviewCount: 143,
    priceLevel: 2,
    imageSeed: "onit-dine-8",
    gallerySeeds: ["onit-dine-8a", "onit-dine-8b", "onit-dine-8c"],
    about:
      "A pastry-forward all-day cafe five minutes from Mount Lavinia beach, known for its viennoiserie and celebration cakes.",
    amenities: ["Outdoor seating", "Free WiFi", "Family friendly"],
    menuHighlights: [
      { id: "r8-1", name: "Butter Croissant", priceLKR: 550, description: "Laminated 48 hours, baked to order." },
      { id: "r8-2", name: "Basque Burnt Cheesecake", priceLKR: 950, description: "Slice, served with berry compote." },
      { id: "r8-3", name: "Iced Pandan Latte", priceLKR: 850, description: "House pandan syrup." },
    ],
    partySizes: [2, 3, 4, 5, 6],
    openHours: standardHours,
    reviews: [
      { id: "r8rev1", author: "Aisha N.", rating: 5, date: "2026-05-28", comment: "The croissants sell out by 10am for good reason." },
    ],
    featured: false,
    phone: "+94 11 273 8850",
  },
];
