import type { Salon } from "../../src/lib/types";

const standardHours = [
  { day: "Mon", hours: "9:00 AM – 8:00 PM" },
  { day: "Tue", hours: "9:00 AM – 8:00 PM" },
  { day: "Wed", hours: "9:00 AM – 8:00 PM" },
  { day: "Thu", hours: "9:00 AM – 8:00 PM" },
  { day: "Fri", hours: "9:00 AM – 8:00 PM" },
  { day: "Sat", hours: "9:00 AM – 9:00 PM" },
  { day: "Sun", hours: "10:00 AM – 6:00 PM" },
];

export const salons: Omit<Salon, "activePromotions" | "mioSalonEmbedCode" | "hidden">[] = [
  {
    id: "s1",
    slug: "the-parlour-colpetty",
    name: "The Parlour, Colpetty",
    tagline: "Editorial hair and colour in the heart of Colpetty",
    area: "Colpetty (Colombo 3)",
    address: "24 Level Grande, Marine Drive, Colombo 3",
    lat: 6.9147,
    lng: 79.8478,
    categories: ["hair", "skin-facial", "brows-lashes"],
    rating: 4.8,
    reviewCount: 312,
    priceLevel: 3,
    imageSeed: "onit-salon-1",
    gallerySeeds: ["onit-salon-1a", "onit-salon-1b", "onit-salon-1c"],
    about:
      "A light-filled studio overlooking Galle Face Green, The Parlour is known for precision cuts and considered colour work. Every appointment starts with an unhurried consultation.",
    amenities: ["Air conditioned", "Free WiFi", "Card & QR payments", "Valet parking"],
    services: [
      { id: "s1-1", name: "Signature Cut & Finish", category: "hair", durationMins: 60, priceLKR: 3800, description: "Consultation, precision cut and blow-dry finish." },
      { id: "s1-2", name: "Global Colour", category: "hair", durationMins: 120, priceLKR: 9500, description: "Full head colour with gloss treatment." },
      { id: "s1-3", name: "Balayage", category: "hair", durationMins: 180, priceLKR: 16500, description: "Hand-painted balayage with toner and finish." },
      { id: "s1-4", name: "Express Facial", category: "skin-facial", durationMins: 45, priceLKR: 5500, description: "Deep cleanse, exfoliation and hydration mask." },
      { id: "s1-5", name: "Brow Shape & Tint", category: "brows-lashes", durationMins: 30, priceLKR: 2200, description: "Shape, tint and finish." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Amaya S.", rating: 5, date: "2026-06-02", comment: "Best balayage I've had in Colombo. Booked in under a minute." },
      { id: "r2", author: "Ridma F.", rating: 5, date: "2026-05-18", comment: "Precise cut, lovely space, on time as booked." },
      { id: "r3", author: "Zara N.", rating: 4, date: "2026-04-30", comment: "Great colour work, slightly pricier but worth it." },
    ],
    featured: true,
    phone: "+94 11 234 5678",
    whatsappNumber: "+94 11 234 5678",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s2",
    slug: "gloss-bar-bambalapitiya",
    name: "Gloss Bar",
    tagline: "Nail studio for clean, long-lasting manicures",
    area: "Bambalapitiya (Colombo 4)",
    address: "112 Galle Road, Bambalapitiya, Colombo 4",
    lat: 6.8905,
    lng: 79.8560,
    categories: ["nails", "brows-lashes"],
    rating: 4.7,
    reviewCount: 208,
    priceLevel: 2,
    imageSeed: "onit-salon-2",
    gallerySeeds: ["onit-salon-2a", "onit-salon-2b", "onit-salon-2c"],
    about:
      "Gloss Bar specialises in gel and structured manicures with a strong focus on nail health. Instruments are sterilised between every client.",
    amenities: ["Air conditioned", "Free WiFi", "Card & QR payments"],
    services: [
      { id: "s2-1", name: "Classic Manicure", category: "nails", durationMins: 40, priceLKR: 2500, description: "Shape, cuticle care and polish." },
      { id: "s2-2", name: "Gel Manicure", category: "nails", durationMins: 60, priceLKR: 4200, description: "Gel overlay with a 2-week finish." },
      { id: "s2-3", name: "Classic Pedicure", category: "nails", durationMins: 50, priceLKR: 3200, description: "Soak, exfoliation and polish." },
      { id: "s2-4", name: "Gel Mani + Pedi Combo", category: "nails", durationMins: 100, priceLKR: 7200, description: "Full gel manicure and pedicure." },
      { id: "s2-5", name: "Classic Lash Set", category: "brows-lashes", durationMins: 90, priceLKR: 6500, description: "Semi-permanent classic lash extensions." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Nethmi K.", rating: 5, date: "2026-06-10", comment: "My gels always last 3 weeks. Never chip." },
      { id: "r2", author: "Ishara D.", rating: 4, date: "2026-05-02", comment: "Clean space, friendly staff, good value." },
    ],
    featured: true,
    phone: "+94 11 245 8890",
    whatsappNumber: "+94 11 245 8890",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s3",
    slug: "willow-spa-rajagiriya",
    name: "Willow Spa & Wellness",
    tagline: "Quiet-hours spa treatments for total reset days",
    area: "Rajagiriya",
    address: "45 Nawala Road, Rajagiriya",
    lat: 6.9095,
    lng: 79.8985,
    categories: ["spa-massage", "skin-facial"],
    rating: 4.9,
    reviewCount: 176,
    priceLevel: 3,
    imageSeed: "onit-salon-3",
    gallerySeeds: ["onit-salon-3a", "onit-salon-3b", "onit-salon-3c"],
    about:
      "Set back from the road behind a walled garden, Willow is Rajagiriya's quietest spa — six treatment rooms, no shared waiting areas, and therapists trained in Ayurvedic and Swedish technique.",
    amenities: ["Air conditioned", "Private treatment rooms", "Card & QR payments", "Free parking"],
    services: [
      { id: "s3-1", name: "Swedish Massage (60 min)", category: "spa-massage", durationMins: 60, priceLKR: 6500, description: "Full body relaxation massage." },
      { id: "s3-2", name: "Deep Tissue Massage (90 min)", category: "spa-massage", durationMins: 90, priceLKR: 9800, description: "Targeted deep tissue release." },
      { id: "s3-3", name: "Ayurvedic Herbal Massage", category: "spa-massage", durationMins: 75, priceLKR: 8500, description: "Warm herbal oil massage, traditional technique." },
      { id: "s3-4", name: "Radiance Facial", category: "skin-facial", durationMins: 60, priceLKR: 7500, description: "Brightening facial with vitamin C serum." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Vinodh P.", rating: 5, date: "2026-06-14", comment: "Most relaxing hour of my month, every month." },
      { id: "r2", author: "Chami R.", rating: 5, date: "2026-05-27", comment: "Private rooms make a huge difference." },
    ],
    featured: true,
    phone: "+94 11 288 1102",
    whatsappNumber: "+94 11 288 1102",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s4",
    slug: "the-gentlemens-room-nugegoda",
    name: "The Gentlemen's Room",
    tagline: "Barbering and grooming built around your schedule",
    area: "Nugegoda",
    address: "8 High Level Road, Nugegoda",
    lat: 6.8649,
    lng: 79.8997,
    categories: ["mens-grooming", "hair"],
    rating: 4.6,
    reviewCount: 264,
    priceLevel: 1,
    imageSeed: "onit-salon-4",
    gallerySeeds: ["onit-salon-4a", "onit-salon-4b", "onit-salon-4c"],
    about:
      "A classic barbershop with modern booking — skin fades, beard sculpting and hot towel shaves from barbers who've each trained for over a decade.",
    amenities: ["Air conditioned", "Free WiFi", "Card & QR payments"],
    services: [
      { id: "s4-1", name: "Classic Haircut", category: "mens-grooming", durationMins: 30, priceLKR: 1500, description: "Cut and style, any length." },
      { id: "s4-2", name: "Skin Fade", category: "mens-grooming", durationMins: 40, priceLKR: 2000, description: "Precision fade with detailing." },
      { id: "s4-3", name: "Beard Sculpt & Hot Towel", category: "mens-grooming", durationMins: 30, priceLKR: 1800, description: "Shape, trim and hot towel finish." },
      { id: "s4-4", name: "Cut + Beard Combo", category: "mens-grooming", durationMins: 60, priceLKR: 3200, description: "Full haircut and beard grooming." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Dinuka W.", rating: 5, date: "2026-06-08", comment: "Booked a 6pm slot on my phone, walked in, no wait." },
      { id: "r2", author: "Sahan M.", rating: 4, date: "2026-05-11", comment: "Consistent fades every time." },
    ],
    featured: false,
    phone: "+94 11 278 3345",
    whatsappNumber: "+94 11 278 3345",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s5",
    slug: "bloom-bridal-studio-cinnamon-gardens",
    name: "Bloom Bridal Studio",
    tagline: "Bridal and occasion makeup, from trials to the big day",
    area: "Cinnamon Gardens (Colombo 7)",
    address: "17 Ward Place, Colombo 7",
    lat: 6.9081,
    lng: 79.8657,
    categories: ["bridal-makeup", "hair", "skin-facial"],
    rating: 4.9,
    reviewCount: 143,
    priceLevel: 3,
    imageSeed: "onit-salon-5",
    gallerySeeds: ["onit-salon-5a", "onit-salon-5b", "onit-salon-5c"],
    about:
      "Bloom has styled over 800 Colombo brides. Packages include a trial session, and the team travels for wedding-day appointments across the city.",
    amenities: ["Air conditioned", "Private studio", "Card & QR payments", "On-location available"],
    services: [
      { id: "s5-1", name: "Bridal Trial", category: "bridal-makeup", durationMins: 90, priceLKR: 15000, description: "Full look trial ahead of the wedding day." },
      { id: "s5-2", name: "Bridal Day Package", category: "bridal-makeup", durationMins: 180, priceLKR: 65000, description: "Hair, makeup and touch-ups for the full day." },
      { id: "s5-3", name: "Occasion Makeup", category: "bridal-makeup", durationMins: 60, priceLKR: 8500, description: "Makeup application for a special event." },
      { id: "s5-4", name: "Updo & Styling", category: "hair", durationMins: 60, priceLKR: 7000, description: "Formal hair styling for events." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Tehani J.", rating: 5, date: "2026-03-22", comment: "They made my wedding morning completely stress-free." },
      { id: "r2", author: "Ashiqa M.", rating: 5, date: "2026-02-14", comment: "The trial session made all the difference." },
    ],
    featured: true,
    phone: "+94 11 269 7712",
    whatsappNumber: "+94 11 269 7712",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s6",
    slug: "clean-lines-wellawatte",
    name: "Clean Lines Nail & Brow Bar",
    tagline: "Fast, tidy nail and brow appointments",
    area: "Wellawatte (Colombo 6)",
    address: "156 Galle Road, Wellawatte, Colombo 6",
    lat: 6.8779,
    lng: 79.8608,
    categories: ["nails", "brows-lashes", "waxing-threading"],
    rating: 4.5,
    reviewCount: 191,
    priceLevel: 1,
    imageSeed: "onit-salon-6",
    gallerySeeds: ["onit-salon-6a", "onit-salon-6b", "onit-salon-6c"],
    about:
      "A no-frills, efficiently run studio for quick manicures, threading and brow tints between meetings — most appointments run within 5 minutes of the booked time.",
    amenities: ["Air conditioned", "Card & QR payments"],
    services: [
      { id: "s6-1", name: "Classic Manicure", category: "nails", durationMins: 35, priceLKR: 2000, description: "Shape, cuticle care and polish." },
      { id: "s6-2", name: "Eyebrow Threading", category: "waxing-threading", durationMins: 15, priceLKR: 400, description: "Precision brow threading." },
      { id: "s6-3", name: "Full Face Threading", category: "waxing-threading", durationMins: 25, priceLKR: 900, description: "Full face hair removal by thread." },
      { id: "s6-4", name: "Brow Tint", category: "brows-lashes", durationMins: 15, priceLKR: 1200, description: "Semi-permanent brow tint." },
      { id: "s6-5", name: "Half Leg Wax", category: "waxing-threading", durationMins: 30, priceLKR: 1800, description: "Warm wax hair removal, half leg." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Hansi B.", rating: 4, date: "2026-06-01", comment: "Quick and tidy, exactly what I need on a lunch break." },
      { id: "r2", author: "Roshel A.", rating: 5, date: "2026-05-06", comment: "Threading here is the best in the area." },
    ],
    featured: false,
    phone: "+94 11 251 4423",
    whatsappNumber: "+94 11 251 4423",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s7",
    slug: "aura-hair-lounge-thimbirigasyaya",
    name: "Aura Hair Lounge",
    tagline: "Curly and textured hair specialists",
    area: "Thimbirigasyaya",
    address: "63 Independence Avenue, Thimbirigasyaya",
    lat: 6.8977,
    lng: 79.8737,
    categories: ["hair"],
    rating: 4.7,
    reviewCount: 122,
    priceLevel: 2,
    imageSeed: "onit-salon-7",
    gallerySeeds: ["onit-salon-7a", "onit-salon-7b", "onit-salon-7c"],
    about:
      "Aura built its reputation on curly and textured hair — cuts, treatments and colour that work with your natural texture rather than against it.",
    amenities: ["Air conditioned", "Free WiFi", "Card & QR payments"],
    services: [
      { id: "s7-1", name: "Curl Cut & Definition", category: "hair", durationMins: 75, priceLKR: 4500, description: "Dry cut for curl shape, styled to finish." },
      { id: "s7-2", name: "Deep Conditioning Treatment", category: "hair", durationMins: 45, priceLKR: 4000, description: "Intensive moisture treatment." },
      { id: "s7-3", name: "Keratin Smoothing", category: "hair", durationMins: 150, priceLKR: 14000, description: "Smoothing treatment, lasts up to 4 months." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Yasmin C.", rating: 5, date: "2026-05-30", comment: "First salon in Colombo that actually gets curly hair." },
    ],
    featured: false,
    phone: "+94 11 259 9021",
    whatsappNumber: "+94 11 259 9021",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
  {
    id: "s8",
    slug: "the-glow-room-mount-lavinia",
    name: "The Glow Room",
    tagline: "Facials and skin treatments by the coast",
    area: "Mount Lavinia",
    address: "22 Hotel Road, Mount Lavinia",
    lat: 6.8389,
    lng: 79.8653,
    categories: ["skin-facial", "brows-lashes", "waxing-threading"],
    rating: 4.6,
    reviewCount: 158,
    priceLevel: 2,
    imageSeed: "onit-salon-8",
    gallerySeeds: ["onit-salon-8a", "onit-salon-8b", "onit-salon-8c"],
    about:
      "A skin-first studio with estheticians trained in HydraFacial and chemical peel protocols, five minutes from Mount Lavinia beach.",
    amenities: ["Air conditioned", "Free WiFi", "Card & QR payments", "Free parking"],
    services: [
      { id: "s8-1", name: "HydraFacial", category: "skin-facial", durationMins: 60, priceLKR: 9500, description: "Deep cleanse, extraction and hydration." },
      { id: "s8-2", name: "Classic Facial", category: "skin-facial", durationMins: 45, priceLKR: 5000, description: "Cleanse, steam, mask and massage." },
      { id: "s8-3", name: "Lash Lift & Tint", category: "brows-lashes", durationMins: 45, priceLKR: 4500, description: "Natural lash lift with tint." },
      { id: "s8-4", name: "Underarm Wax", category: "waxing-threading", durationMins: 15, priceLKR: 800, description: "Warm wax hair removal." },
    ],
    openHours: standardHours,
    reviews: [
      { id: "r1", author: "Piyumi G.", rating: 5, date: "2026-06-05", comment: "My skin has never looked better. Booking was instant." },
      { id: "r2", author: "Nadia S.", rating: 4, date: "2026-04-19", comment: "Lovely space, a little hard to find parking." },
    ],
    featured: false,
    phone: "+94 11 273 6650",
    whatsappNumber: "+94 11 273 6650",
    coverImage: null,
    galleryImages: [],
    pricingRules: [],
    cancellationFeeEnabled: false,
    cancellationFeePercent: 20,
    noShowFeeEnabled: false,
    noShowFeePercent: 20,
  },
];
